services:

  web:
    image: nginx
    volumes:
      - ./html:/usr/share/nginx/html
#      - ./html:/var/www/html
      - ./web-config/default.conf:/etc/nginx/conf.d/default.conf
    links:
      - php-fpm
    ports:
      - 81:80
    environment:
      - NGINX_HOST=foobar.com
      - NGINX_PORT=80
  php-fpm:
    image: bitnami/php-fpm
    volumes:
      - ./html:/usr/share/nginx/html

  db:
    image: mariadb:10.6
    volumes:
      - ./database:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MARIADB_ROOT_PASSWORD: 4321

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
